export const privacyPolicy = `
## Privacy Policy

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

### Interpretation and Definitions

#### Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

#### Definitions
For the purposes of this Privacy Policy:
* **Account** means a unique account created for You to access our Service or parts of our Service.
* **Affiliate** means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
* **Business**, for the purpose of CCPA/CPRA, refers to the Company as the legal entity that collects Consumers’ personal information and determines the purposes and means of the processing of Consumers’ personal information.
* **Company** (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to F2 Nutrition, LLC dba: BioLongevity Labs, PO Box 916, Bath OH 44210.
* **Cookies** are small files that are placed on Your computer, mobile device or any other device by a website.
* **Country** refers to: Ohio, United States.
* **Device** means any device that can access the Service such as a computer, a cellphone or a digital tablet.
* **Personal Data** is any information that relates to an identified or identifiable individual.
* **Service** refers to the Website.
* **Service Provider** means any natural or legal person who processes the data on behalf of the Company.
* **Usage Data** refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
* **Website** refers to BioLongevity Labs, accessible from https://biolongevitylabs.com

### Collecting and Using Your Personal Data

#### Types of Data Collected

##### Personal Data
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
* Email address
* First name and last name
* Phone number
* Address, State, Province, ZIP/Postal code, City

##### Usage Data
Usage Data is collected automatically when using the Service.
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

### Use of Your Personal Data
The Company may use Personal Data for the following purposes:
* **To provide and maintain our Service**, including to monitor the usage of our Service.
* **To manage Your Account**: to manage Your registration as a user of the Service.
* **For the performance of a contract**: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.
* **To contact You**: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.
* **To provide You** with news, special offers and general information about other goods, services and events which we offer.

### Disclosure of Your Personal Data
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

### Security of Your Personal Data
The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
`;

export const ruoPolicy = `
## Research Use Only Policy

### Intended Purpose
Research Use Only (“RUO”) products sold here are intended solely for basic research, pharmaceutical research, or the development of new tests, not for diagnosing a disease or condition in any patient. Misusing these products is illegal.

When purchasing RUO products on this site, you agree that the statements you’ve made herein are true and factual, and you consent to IP address verification, request for authentication of information provided, & other verification methods by F2 Nutrition dba BioLongevity Labs (“the Company”) to validate that the information provided is true in its sole discretion.

The Company reserves the right to cancel any order at any time for providing false information and the customer indemnifies and holds harmless the Company for any and all harm caused to the customer by using the products outside of in vitro study, research use, or guidelines as defined by the FDA.

Unapproved and improper uses of these products is a breach of FDA Law, and company terms and conditions, and shall result in immediate termination of customer account and report to appropriate authorities. The statements on this website and products have NOT been evaluated by the Food and Drug Administration (FDA) and are not intended to diagnose, treat, cure, or prevent any disease. Using these products in humans or animals can cause injury.

### Submission of Studies and Research
By purchasing research products on this site, you agree to submit at least one study and research results, for quality control & community research purposes, at least one time annually into your customer account to keep your researcher validation active.

### Compliance
All research chemicals are for in-vitro laboratory research use only. They are not for human or animal use. Compliance with all local, state, and federal laws and regulations is the sole responsibility of the purchaser.
`;
